package view;

import controller.Disciplina_AreaConhecimentoController;
import controller.FuncionarioController;
import controller.LoginController;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import model.AreaConhecimentoModel;
import model.DisciplinaModel;
import model.FuncionarioModel;

/**
 *
 * @author José Orlando
 */
public class ViewFuncionario extends javax.swing.JFrame {

    String boasVindas = "FUNCIONÁRIOS - "
            + ViewLogin.usuSelecionado.getNome()
            + " - Modo: "
            + ViewLogin.usuSelecionado.getCargo();

    FuncionarioModel funcionarioModel = new FuncionarioModel();
    FuncionarioController funcionarioController = new FuncionarioController();
    DisciplinaModel disciplinaModel = new DisciplinaModel();
    AreaConhecimentoModel acModel = new AreaConhecimentoModel();
    Disciplina_AreaConhecimentoController disACController = new Disciplina_AreaConhecimentoController();

    List<DisciplinaModel> listaDisciplinas = disACController.getListaDisciplinasController("");
    List<AreaConhecimentoModel> listaAC = disACController.getListaAreaConhecimentosController();
    LoginController loginController = new LoginController();
    String cadAlt = "cad";

    /**
     * Creates new form ViewFuncionario
     */
    public ViewFuncionario() {
        initComponents();
        setLocationRelativeTo(null);
        carregarTabela();
        carregarComboBox();

        InputMap inputMap = this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "forward");
        this.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMap);
        this.getRootPane().getActionMap().put("forward", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent arg0) {
                jbSalvarActionPerformed(arg0);
            }

        });

    }

    private void carregarComboBox() {
        String[] disciplinas = new String[listaDisciplinas.size()];
        for (int i = 0; i < listaDisciplinas.size(); i++) {
            disciplinas[i] = listaDisciplinas.get(i).getNome();
        }
        jcbLeciona.setModel(new javax.swing.DefaultComboBoxModel<>(disciplinas));

        String[] areas_conhecimento = new String[listaAC.size()];
        for (int i = 0; i < listaAC.size(); i++) {
            areas_conhecimento[i] = listaAC.get(i).getNome();
        }
        jcbCoordena.setModel(new javax.swing.DefaultComboBoxModel<>(areas_conhecimento));
    }

    private void limparFormularios() {
        jtfId.setText("");
        jtfNome.setText("");
        jtfLogin.setText("");
        jpfSenha.setText("");
        jcbCargo.setSelectedIndex(0);
        jcbLeciona.setSelectedIndex(0);
        jcbCoordena.setSelectedIndex(0);
    }

    private void carregarTabela() {
        List<FuncionarioModel> listaFuncionario;
        listaFuncionario = funcionarioController.getListaFuncionariosController();

        DefaultTableModel tabela = (DefaultTableModel) jTabela.getModel();
        tabela.setNumRows(0);

        for (int i = 0; i < listaFuncionario.size(); i++) {
            tabela.addRow(new Object[]{
                listaFuncionario.get(i).getId(),
                listaFuncionario.get(i).getNome(),
                listaFuncionario.get(i).getCargo(),
                listaFuncionario.get(i).getLogin(),
                listaFuncionario.get(i).getLeciona(),
                listaFuncionario.get(i).getCoordena()
            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfId = new javax.swing.JTextField();
        jtfNome = new javax.swing.JTextField();
        jtfLogin = new javax.swing.JTextField();
        jcbCargo = new javax.swing.JComboBox<>();
        jpfSenha = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jcbLeciona = new javax.swing.JComboBox<>();
        jcbCoordena = new javax.swing.JComboBox<>();
        jbSalvar = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(boasVindas);
        setResizable(false);

        jTabela.setAutoCreateRowSorter(true);
        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Cargo", "Login", "Leciona", "Coordena"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTabela);
        if (jTabela.getColumnModel().getColumnCount() > 0) {
            jTabela.getColumnModel().getColumn(0).setMinWidth(25);
            jTabela.getColumnModel().getColumn(0).setPreferredWidth(25);
            jTabela.getColumnModel().getColumn(0).setMaxWidth(25);
            jTabela.getColumnModel().getColumn(1).setMinWidth(100);
            jTabela.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTabela.getColumnModel().getColumn(1).setMaxWidth(100);
            jTabela.getColumnModel().getColumn(3).setMinWidth(70);
            jTabela.getColumnModel().getColumn(3).setPreferredWidth(70);
            jTabela.getColumnModel().getColumn(3).setMaxWidth(70);
        }

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Id");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Cargo");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Login");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Senha");

        jtfId.setEditable(false);

        jcbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coordenador", "Diretor", "Professor" }));
        jcbCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCargoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Leciona");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Coordena");

        jcbLeciona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbLeciona.setEnabled(false);

        jcbCoordena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbSalvar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-mais-30.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbAlterar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-exchange-money-30.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbExcluir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-cancelar-30.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbLimpar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-apagar-30.png"))); // NOI18N
        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbVoltar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-mova-à-esquerda-30.png"))); // NOI18N
        jbVoltar.setText("Voltar");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbLeciona, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbCoordena, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel2)
                                        .addGap(386, 386, 386)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jtfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(220, 220, 220)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addComponent(jbExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addComponent(jpfSenha))
                            .addComponent(jbVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(19, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbAlterar, jbExcluir, jbLimpar, jbVoltar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jcbLeciona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jcbCoordena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbSalvar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbVoltar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        new ViewPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbVoltarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        int linha = jTabela.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um funcionario para apagar.");
        } else {
            if (JOptionPane.showConfirmDialog(this, "Deseja excluir o funcionário selecionado?", "ATENÇÃO!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0) {
                int codigo = (int) jTabela.getValueAt(linha, 0);
                if (funcionarioController.excluirFuncionarioController(codigo)) {
                    carregarTabela();
                    JOptionPane.showMessageDialog(this, "Funcionário excluído com sucesso.");
                } else {
                    JOptionPane.showMessageDialog(this, "Falha ao excluir.\nFuncionário relacionado a outro registro no sistema.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }

        }

    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jcbCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCargoActionPerformed
        switch (jcbCargo.getSelectedItem().toString()) {
            case "Coordenador":
                jcbLeciona.setEnabled(false);
                jcbCoordena.setEnabled(true);
                break;
            case "Diretor":
                jcbLeciona.setEnabled(false);
                jcbCoordena.setEnabled(false);
                break;
            case "Professor":
                jcbLeciona.setEnabled(true);
                jcbCoordena.setEnabled(false);
                break;
        }
    }//GEN-LAST:event_jcbCargoActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed

        funcionarioModel = new FuncionarioModel();
        funcionarioModel.setNome(jtfNome.getText());
        funcionarioModel.setLogin(jtfLogin.getText());
        funcionarioModel.setSenha(String.valueOf(jpfSenha.getPassword()));
        funcionarioModel.setCargo(jcbCargo.getSelectedItem().toString());

        if (jcbCargo.getSelectedItem().toString().equals("Professor")) {
            for (int i = 0; i < listaDisciplinas.size(); i++) {
                if (jcbLeciona.getSelectedItem().toString() == listaDisciplinas.get(i).getNome()) {
                    funcionarioModel.setLeciona(listaDisciplinas.get(i).getId());
                }
            }
        }

        if (jcbCargo.getSelectedItem().toString().equals("Coordenador")) {
            for (int i = 0; i < listaAC.size(); i++) {
                if (jcbCoordena.getSelectedItem().toString() == listaAC.get(i).getNome()) {
                    funcionarioModel.setCoordena(listaAC.get(i).getId());
                }
            }
        }

        if (!validaLogin()) {
            JOptionPane.showMessageDialog(this, "Login já utilizado.\nCadastro não efetuado.", "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (!validaCamposPreenchidos()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos para efetuar o cadastro.", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            if (cadAlt.equals("cad")) {
                String msgRetorno = funcionarioController.salvarFuncionarioController(funcionarioModel);
                if (msgRetorno.equals("")) {
                    JOptionPane.showMessageDialog(this, "Cadastrado com sucesso.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                    carregarTabela();
                    limparFormularios();
                } else {
                    JOptionPane.showMessageDialog(this, msgRetorno + "\nCadastro não efetuado.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                funcionarioModel.setId(Integer.parseInt(jtfId.getText()));
                String msgRetorno = funcionarioController.atualizarFuncionarioController(funcionarioModel);
                if (msgRetorno.equals("")) {
                    JOptionPane.showMessageDialog(this, "Alterado com sucesso.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                    carregarTabela();
                    cadAlt = "cad";
                    jbExcluir.setEnabled(true);
                    jTabela.setEnabled(true);
                    limparFormularios();
                } else {
                    JOptionPane.showMessageDialog(this, msgRetorno + "\nAlteração não efetuada.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private boolean validaLogin() {
        List<String> listaLogins = loginController.listaLoginsController();
        boolean salva = true;
        for (String login : listaLogins) {
            if (funcionarioModel.getLogin().equalsIgnoreCase(login) && cadAlt.equals("cad")) {
                salva = false;
            } else if (cadAlt.equals("alt")) {
                if (!jTabela.getValueAt(jTabela.getSelectedRow(), 3).toString().equalsIgnoreCase(funcionarioModel.getLogin()) && funcionarioModel.getLogin().equalsIgnoreCase(login)) {
                    salva = false;
                }
            }
        }
        return salva;
    }

    private boolean validaCamposPreenchidos() {
        if (jtfNome.getText().equals("")
                || jtfLogin.getText().equals("")
                || jpfSenha.getText().equals("")) {
            return false;
        } else {
            return true;
        }
    }

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limparFormularios();
        cadAlt = "cad";
        jbExcluir.setEnabled(true);
        jTabela.setEnabled(true);
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        cadAlt = "alt";
        int linha = jTabela.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um funcionário para alterar.");
        } else {

            jtfId.setText(jTabela.getValueAt(linha, 0).toString());
            jtfNome.setText(jTabela.getValueAt(linha, 1).toString());
            jcbCargo.setSelectedItem(jTabela.getValueAt(linha, 2).toString());
            jtfLogin.setText(jTabela.getValueAt(linha, 3).toString());

            if (jcbLeciona.isEnabled()) {
                jcbLeciona.setSelectedItem(jTabela.getValueAt(linha, 4).toString());
            }
            if (jcbCoordena.isEnabled()) {
                jcbCoordena.setSelectedItem(jTabela.getValueAt(linha, 5).toString());
            }
            carregarSenhaFuncionario(linha);
            
            jbExcluir.setEnabled(false);
            jTabela.setEnabled(false);
        }

    }//GEN-LAST:event_jbAlterarActionPerformed

    private void carregarSenhaFuncionario(int linha){
        List<FuncionarioModel> listaFuncionario;
            listaFuncionario = funcionarioController.getListaFuncionariosController();
            for (int i = 0; i < listaFuncionario.size(); i++) {
                if ((int) jTabela.getValueAt(linha, 0) == listaFuncionario.get(i).getId()) {
                    jpfSenha.setText(listaFuncionario.get(i).getSenha());
                }
            }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabela;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JComboBox<String> jcbCargo;
    private javax.swing.JComboBox<String> jcbCoordena;
    private javax.swing.JComboBox<String> jcbLeciona;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfLogin;
    private javax.swing.JTextField jtfNome;
    // End of variables declaration//GEN-END:variables
}
